### ISSUE TITLE
2D FID crash jcampconverter

### ISSUE THREAD

**Issue by jobo322** [cheminfo/jcampconverter#67]
the file will be loaded in the related branch as a failing test case

**Comment by lpatiny** [comment]
@jobo322 please create the branch and also a 'pr --draft' so that we can track it easily. You may also add the link in this issue.

**Comment by lpatiny** [comment]
I'm wondering if this file has the same issue

[hmqc.ser.dx.zip](https://github.com/cheminfo/jcampconverter/files/9879530/hmqc.ser.dx.zip)

We get this problem
```
Uncaught Error: Problem with determination of gyromagnetic ratio
    at postProcessingNMR (postProcessingNMR.js:82:31)
    at postProcessing (postProcessing.js:8:5)
    at convert (convert.js:378:5)
    at fromJCAMP (fromJCAMP.js:18:20)
    at processJcamp (readJcamp.js:19:19)
    at readJcamp (readJcamp.js:7:12)
    at async read (read.js:43:50)
```

**Comment by jobo322** [comment]
in this case, the nucleus has one missing



![Image](https://user-images.githubusercontent.com/12143935/216228145-ef11b726-b7bc-4143-afcc-2e0c585fcbd0.png)
